name: providers/inmemory
on:
  pull_request:
    paths:
    - 'providers/inmemory/*'
  push:
    paths:
    - 'providers/inmemory/*'
jobs:
  test:
    strategy:
      matrix:
        go: ['1.14', '1.13']
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: ${{ matrix.os }} ${{ matrix.go }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Go ${{ matrix.go }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - run: go version
      - name: Test
        working-directory: ./providers/inmemory
        run: go test -race -coverprofile="coverage.out" -covermode="atomic"
      - name: Upload Coverage
        uses: codecov/codecov-action@v1.0.7
        with:
          file: ./providers/inmemory/coverage.out
          fail_ci_if_error: true
