on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # Install Go
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      # Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v2
      # Run the test suite
      - name: Test
        run: find . -name go.mod -execdir go test -v ./... -coverprofile=coverage.out -covermode=atomic \;
      # Join coverage reports together
      - name: Join Coverage Reports
        run: |
          echo "mode: atomic" > report.out
          for f in $(find . -name coverage.out); do
            cat $f | grep -v "mode: atomic"  >> report.out;
          done
      # Upload coverage report to codecov
      - name: Upload Coverage Report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: report.out
