on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      fail-fast: true
      matrix:
        go-version: [1.14.x, 1.15.x]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Test
        run: find . -name go.mod -execdir go test -v ./... -cover \;
